// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// zpath
Rcpp::List zpath(arma::mat beta, double phi, const arma::mat& logy, const arma::mat& y, const arma::mat& x, const Rcpp::List& txi, const Rcpp::List& Pidx, double lambda, int n, int D, int p, int K, const arma::vec& pen, int maxit, double tol);
RcppExport SEXP _Compositionalridge_zpath(SEXP betaSEXP, SEXP phiSEXP, SEXP logySEXP, SEXP ySEXP, SEXP xSEXP, SEXP txiSEXP, SEXP PidxSEXP, SEXP lambdaSEXP, SEXP nSEXP, SEXP DSEXP, SEXP pSEXP, SEXP KSEXP, SEXP penSEXP, SEXP maxitSEXP, SEXP tolSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< double >::type phi(phiSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type logy(logySEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type txi(txiSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type Pidx(PidxSEXP);
    Rcpp::traits::input_parameter< double >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< int >::type D(DSEXP);
    Rcpp::traits::input_parameter< int >::type p(pSEXP);
    Rcpp::traits::input_parameter< int >::type K(KSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type pen(penSEXP);
    Rcpp::traits::input_parameter< int >::type maxit(maxitSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    rcpp_result_gen = Rcpp::wrap(zpath(beta, phi, logy, y, x, txi, Pidx, lambda, n, D, p, K, pen, maxit, tol));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_Compositionalridge_zpath", (DL_FUNC) &_Compositionalridge_zpath, 15},
    {NULL, NULL, 0}
};

RcppExport void R_init_Compositionalridge(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
